// 别名设置
import { resolve } from "path";
// ts类型检测
import { defineConfig } from "vite";
// 注入插件
import inject from "@rollup/plugin-inject";
// vite内vue插件
import vuePlugin from "@vitejs/plugin-vue";
// 静态资源压缩插件
import compressPlugin from "vite-plugin-compression";
// 主题配置插件
import themePreprocessorPlugin from "@zougt/vite-plugin-theme-preprocessor";
// wasm plugin
import wasmPack from 'vite-plugin-wasm-pack';

// According to the doc: https://vitejs.dev/guide/env-and-mode.html#env-variables
// I need to prefix env variables in .env with "VITE_" in order to expose them.
// But these variables are automatically generated by Dfinity, and it is tedious to prefix
// them every time.
// So I took advaice from this post: 
// https://stackoverflow.com/questions/70709987/how-to-load-environment-variables-from-env-file-using-vite
// and use `dotenv.config()` to pour all variables into `process.env`
// and then use `define` to expose them into client according to here: 
// https://vitejs.dev/config/shared-options.html#envprefix
import dotenv from 'dotenv';
dotenv.config(); // load env vars from .env

// 配置项
export default defineConfig({
  root: 'src/faceless_frontend',
  // 资源跟路径
  base: "/",
  define: {
    'import.meta.env.DFX_NETWORK': JSON.stringify(process.env.DFX_NETWORK),
    "import.meta.env.FACELESS_BACKEND_CANISTER_ID": JSON.stringify(process.env.CANISTER_ID_faceless_dfinity_backend),
    "import.meta.env.LEDGER_CANISTER_ID": JSON.stringify(process.env.CANISTER_ID_ledger)
  },
  // vue适配插件
  plugins: [
    // 加载插件
    vuePlugin(),
    // 压缩插件
    compressPlugin({
      ext: ".gz",
      verbose: true,
      disable: true,
      threshold: 10240,
      algorithm: "gzip",
      deleteOriginFile: false,
    }),
    // 主题插件
    themePreprocessorPlugin({
      scss: {
        // 是否启用任意主题色模式
        arbitraryMode: false,
        // 预处理器的变量文件
        multipleScopeVars: [
          {
            scopeName: "theme-dark",
            path: resolve("src/faceless_frontend/src/assets/style/theme/dark.scss"),
          },
          {
            scopeName: "theme-light",
            path: resolve("src/faceless_frontend/src/assets/style/theme/light.scss"),
          },
        ],
        // 默认主题
        defaultScopeName: "theme-dark",
        // 在生产模式是否抽取独立的主题css文件
        extract: false,
      },
    }),
    // wasm wrapper for faceless crypto lib written in Rust
    wasmPack('./src/faceless_frontend/faceless-wasm-wrapper'),
  ],
  // JSON解释方式
  json: {
    stringify: true,
  },
  // 资源内联限制
  build: {
    sourcemap: false,

    minify: "esbuild",

    assetsInlineLimit: 0,

    reportCompressedSize: false,

    commonjsOptions: { transformMixedEsModules: true },

    rollupOptions: { 
      plugins: [inject({ Buffer: ["buffer", "Buffer"] })],      
      // input: {
      //   app: resolve(__dirname, 'src/faceless_frontend/index.html'),
      // }
    },
    // Having '../../' because the root is 'src/faceless_frontend' that has depth of two levels
    outDir: '../../dist',
  },
  // 别名配置
  resolve: {
    alias: [
      {
        find: "@",
        replacement: resolve(__dirname, "src/faceless_frontend/src"),
      },
      {
        find: "process",
        replacement: "process/browser",
      },
      {
        find: "stream",
        replacement: "stream-browserify",
      },
      {
        find: "zlib",
        replacement: "browserify-zlib",
      },
      {
        find: "util",
        replacement: "util",
      },
    ],
  },
  // 服务配置（代理模式）
  server: {
    // 端口号
    port: 4944,
    // 地址
    host: "127.0.0.1",
    // 自动打开
    open: false,
    // 代理
    proxy: {
      // 测试
      "/staging": {
        target: "",
        changeOrigin: true,
        rewrite: path => path.replace(/^\/staging/, ""),
      },

      // 正式
      "/production": {
        target: "",
        changeOrigin: true,
        rewrite: path => path.replace(/^\/production/, ""),
      },
      // Need to add this proxy by referring to how Dfinity's `webpack.config.js` is written.
      // The port 4943 is used for the DFX replica server.
      "/api": {
        target: "http://127.0.0.1:4943",
        changeOrigin: true,
        rewrite: path => path.replace(/^\/api/, "/api/"),
      }
    },
  },
  // 预处理器配置
  css: {
    // 样式插件
    postcss: {
      plugins: [
        require("autoprefixer")({ overrideBrowserslist: ["last 20 versions"], grid: true }),
      ],
    },
    // 样式处理
    preprocessorOptions: {
      scss: {
        javascriptEnabled: true,
      },
    },
  },
  
});
